# permissions for end users to edit exampleresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exampleresource-editor-role
rules:
- apiGroups:
  - example.example.com
  resources:
  - exampleresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.example.com
  resources:
  - exampleresources/status
  verbs:
  - get
