# permissions for end users to view exampleresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exampleresource-viewer-role
rules:
- apiGroups:
  - example.example.com
  resources:
  - exampleresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.example.com
  resources:
  - exampleresources/status
  verbs:
  - get
