apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: test-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ExampleResource is the Schema for the exampleresources API
      displayName: Example Resource
      kind: ExampleResource
      name: exampleresources.example.example.com
      version: v1alpha1
  description: Test Operator
  displayName: Test Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test
  links:
  - name: Test Operator
    url: https://test-operator.domain
  maintainers:
  - email: test@test.com
    name: test
  maturity: alpha
  provider:
    name: Test Provider
  version: 0.0.0
